const BOOKS = {
    LOAD_BOOKS: 'LOAD_BOOKS',
    LOAD_BOOKS_SUCCESS: 'LOAD_BOOKS_SUCCESS',
    LOAD_BOOKS_FAIL: 'LOAD_BOOKS_FAIL'
}

const LOAD_MORE = 'LOAD_MORE'

const INCREMENT_BOOKS = 'INCREMENT_BOOKS'

export {
    BOOKS,
    LOAD_MORE,
    INCREMENT_BOOKS
}
