const BOOK = {
    LOAD_BOOK: 'LOAD_BOOK',
    LOAD_BOOK_SUCCESS: 'LOAD_BOOK_SUCCESS',
    LOAD_BOOK_FAIL: 'LOAD_BOOK_FAIL',
    BUY_BOOK: 'BUY_BOOK',
    BUY_BOOK_SUCCESS: 'BUY_BOOK_SUCCESS',
    BUY_BOOK_FAIL: 'BUY_BOOK_FAIL',
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAIL: 'ADD_TO_CART_FAIL'
}

export {
    BOOK
}
