const CART = {
    LOAD_CART: 'LOAD_CART',
    LOAD_CART_SUCCESS: 'LOAD_CART_SUCCESS',
    LOAD_CART_FAIL: 'LOAD_CART_FAIL',
    EMPTY_CART: 'EMPTY_CART',
    EMPTY_CART_SUCCESS: 'EMPTY_CART_SUCCESS',
    EMPTY_CART_FAIL: 'EMPTY_CART_FAIL',
    CHECKOUT_CART: 'CHECKOUT_CART',
    CHECKOUT_CART_SUCCESS: 'CHECKOUT_CART_SUCCESS',
    CHECKOUT_CART_FAIL: 'CHECKOUT_CART_FAIL'
}

const ADDRESS = {
    SAVE_ADDRESS: 'SAVE_ADDRESS',
    SAVE_ADDRESS_SUCCESS: 'SAVE_ADDRESS_SUCCESS',
    SAVE_ADDRESS_FAIL: 'SAVE_ADDRESS_FAIL',
    LOAD_ADDRESS: 'LOAD_ADDRESS',
    LOAD_ADDRESS_SUCCESS: 'LOAD_ADDRESS_SUCCESS',
    LOAD_ADDRESS_FAIL: 'LOAD_ADDRESS_FAIL'
}

export { CART, ADDRESS }
